### ISSUE TITLE
NoResultsError 에러 발생 특정날짜 (아마도 연휴기간)

### ISSUE THREAD

**Issue by jungrammer** [carpedm20/korail2#31]
```
>>> print(korail.search_train('광명', '동대구', '20200129')[0])
[KTX-산천] 1월 29일, 광명~동대구(15:26~16:58) 특실,일반실 41,300원 5%적립

>>> print(korail.search_train('광명', '동대구', '20200122')[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "korail2/korail2.py", line 788, in search_train
    raise NoResultsError()
korail2.korail2.NoResultsError: No Results (None)
```

특정날짜 1월 22~25일까지에는 
NoResultsError 가 발생하는데, 아마 연휴 기간이라서 발생하는 에러 같습니다.

아직까지 코레일톡 공식앱에서는 잘 조회되는걸로는 보입니다.

**Comment by carpedm20** [comment]
제 기억이 맞다면 연휴 기간의 예약은 이 라이브러리에 구현된 api로는 안될겁니다.

**Comment by jungrammer** [comment]
@carpedm20 네 확인감사합니다 :)

**Comment by jungrammer** [comment]
@carpedm20 혹시 수정 및 업데이트 계획은 있으신가요??

**Comment by sng2c** [comment]
명절기차표 예매에 대해서는
설날과 추석, 1년에 2번 수정할 기회가 생기는건데
기회를 살리기가 쉽지 않네요. ㅠㅠ


2020년 1월 20일 (월) 오후 3:43, Junhoi Park <notifications@github.com>님이 작성:
